# A baseline homelabian config to be built off of by derived subimages
# See also: mkosi.conf.d/ for additional configuration snippets

[Output]
Output=homelabian-base
Format=directory

[Build]
EnvironmentFiles=%D/.env # User .env in current working directory (repo root)

[Content]
Bootable=no  # Base is not bootable by itself
RootShell=/bin/bash
Hostname=homelabian

Packages=
    systemd
    systemd-resolved
    udev
    debian-archive-keyring  # Verifying apt package signatures
    passwd                  # User management
    login                   # Allow user login
    systemd-boot-efi        # Required for UKI builds
    systemd-ukify           # Required for UKI builds
    python3
