# Main configuration file for mkosi, building the various sub-images
# See also: mkosi.images/ for sub-image configs

[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64 
Repositories=main,contrib,non-free,non-free-firmware

[Output]
Format=none  # The "main" image just triggers builds of subimages
OutputDirectory=build/

[Build]
Incremental=yes  # Saves time by reusing previous build artifacts
CacheDirectory=build/mkosi.cache/  # Required for incremental builds
ToolsTree=yes  # Uses a known set of tools to build rather than the host's
WithNetwork=yes  # Allows network access during the build process
