# Base configuration file for mkosi, suppporting a minimal build
# See also: mkosi.conf.d/ for additional configuration snippets

[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64 
Repositories=main,contrib,non-free,non-free-firmware

[Output]
Format=disk
OutputDirectory=build/
ImageId=Homelabian
Output=homelabian_image  # If not set, this matches the image ID which changes with each build and spams new artifacts when testing

[Build]
Incremental=yes  # Saves time by reusing previous build artifacts
CacheDirectory=build/mkosi.cache/  # Required for incremental builds
ToolsTree=yes  # Uses a known set of tools to build rather than the host's
EnvironmentFiles=.env
WithNetwork=yes  # Allows network access during the build process

[Environment]
http_proxy=http://127.0.0.1:3142  # Allow `apt-cacher-ng` to be used if installed

[Content]
Bootable=yes  # Ensures the image is bootable
Bootloader=uki  # Uses the Unified Kernel Image

Locale=en_US.UTF-8
LocaleMessages=en_US.UTF-8
Keymap=us
Timezone=America/New_York
RootShell=/bin/bash
Hostname=homelabian

CleanPackageMetadata=no # TODO =yes saves 0.5GB but breaks dpkg in the final image
Packages=
    systemd
    systemd-resolved
    udev
    passwd                  # User management
    debian-archive-keyring  # Verifying apt package signatures
    login                   # Allow user login
    systemd-boot-efi        # Required for UKI builds
    systemd-ukify           # Required for UKI builds
    linux-image-amd64       # Kernel image for x86-64 architecture
    locales                 # Builds binary locale for the system
    python3
    python3-venv
    apt

BuildPackages=
    locales