# Main configuration file for mkosi, orchestrating the image build

[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64 

[Output]
Format=disk

[Build]
Incremental=yes  # Saves time by reusing previous build artifacts
CacheDirectory=/var/tmp/mkosi-cache  # Required for incremental builds
ToolsTree=yes  # Uses a known set of tools to build rather than the host's

EnvironmentFiles=.env

[Content]
RootPassword=toor
Packages=
    systemd
    udev
    passwd                  # User management
    sudo                    # Granting admin privileges
    debian-archive-keyring  # Verifying apt package signatures
    login
    passwd

BuildPackages=
    build-essential,
    curl
