# Userful utilities for managment, debugging, and monitoring

[Content]
Packages=
    man
    procps                  # Process status utilities like `free` and `ps`
    vim
    less
    curl
    wget