# Userful utilities for managment, debugging, and monitoring

[Content]
Packages=
    man
    procps                  # Process status utilities like `free` and `ps`
    vim
    less
    curl
    wget
    plocate
    iputils-ping
    docker-cli
    docker.io
    btop
    git
    iproute2
    tmux
    screen
    etckeeper
    avahi-daemon

BuildPackages=
    make
    gawk