# Security-specific packages and configurations for the image

[Content]
Packages=
	intel-microcode			# Microcode security updates for Intel CPUs
    amd64-microcode			# Microcode security updates for AMD CPUs
	tailscale				# VPN to allow connection to a personal tailnet
	tailscale-archive-keyring
