# Userful utilities for managment, debugging, and monitoring

[Content]
Packages=
    man
    vim
    less
    plocate                 # locate tool to help find files
    # TODO: https://github.com/chaifeng/ufw-docker#solving-ufw-and-docker-issues
    docker.io               # Docker server
    docker-cli              # docker CLI command
    btop                    # Pretty CPU/MEM/PID view/graph tool
    tmux
    screen
    git
    etckeeper               # Tracks changes to `/etc` via git

BuildPackages=
    make
    gawk
