# Security-specific packages and configurations for the image

[Content]
KernelCommandLine=apparmor=1 security=apparmor
Packages=
    sudo
    fail2ban                # Protects against brute-force attacks
	ufw						# Firewall
	unattended-upgrades		# Automatically install security updates
	intel-microcode			# Microcode security updates for Intel CPUs
    amd64-microcode			# Microcode security updates for AMD CPUs
	ca-certificates			# Trusted CA certificates for HTTPS
	needrestart 			# Checks for services that need to be restarted after package upgrades
	openssh-server
	auditd					# Logs security-relevant events to `/var/log/audit/audit.log`
	apparmor				# Media Access Control to control which resources are accessable on a program by program basis
	apparmor-utils
	apparmor-profiles
	apparmor-profiles-extra
	tailscale
	tailscale-archive-keyring
