# Userful utilities for managment, debugging, and monitoring

[Content]
Packages=
    man
    procps                  # Process status utilities like `free` and `ps`
    vim
    less
    curl
    wget
    plocate                 # locate tool to help find files
    iputils-ping            # ping tool
    # TODO: https://github.com/chaifeng/ufw-docker#solving-ufw-and-docker-issues
    docker.io               # Docker server
    docker-cli              # docker CLI command
    btop                    # Pretty CPU/MEM/PID view/graph tool
    git
    iproute2                # replacement for net-utils, includes ifconfig etc.
    tmux
    screen
    etckeeper               # Tracks changes to `/etc` via git
    avahi-daemon            # mDNS support to allow hostname addressing via `homelabian.local`
    bash-completion
    python3-apt             # Allows Ansible to install packages quicker allegedly
    cloud-guest-utils       # growpart to resize rootfs
    e2fsprogs               # resizefs to resize rootfs

BuildPackages=
    make
    gawk