# Userful utilities for managment, debugging, and monitoring

[Content]
Packages=
    procps                  # Process status utilities like `free` and `ps`
    iputils-ping            # ping tool
    iproute2                # replacement for net-utils, includes ifconfig etc.
    avahi-daemon            # mDNS support to allow hostname addressing via `homelabian.local`
    bash-completion
    python3-apt             # Allows Ansible to install packages quicker allegedly
    parted                  # Manage partitions (such as creating a SWAP partition)
    e2fsprogs               # resizefs to resize rootfs
    cloud-guest-utils       # growpart to resize rootfs partition live
    systemd-sysv            # Provides reboot/shutdown commands
    apt
    curl                    # Useful for downloading images to update
    man
    less