# Userful utilities for managment, debugging, and monitoring

[Content]
Packages=
    procps                  # Process status utilities like `free` and `ps`
    iputils-ping            # ping tool
    iproute2                # replacement for net-utils, includes ifconfig etc.
    avahi-daemon            # mDNS support to allow hostname addressing via `homelabian.local`
    bash-completion
    python3-apt             # Allows Ansible to install packages quicker allegedly
    parted                  # Allows Ansible to modify disk partitions
    e2fsprogs               # Allows Ansible to expand the rootfs into a larger partition
    systemd-sysv            # Provides reboot/shutdown commands
    apt
    curl                    # Useful for downloading images to update
    man
    less