# Main homelabian full image, with all bells and whistles
# See also: mkosi.conf.d/ for additional configuration snippets

[Config]
Dependencies=homelabian-base

[Build]
EnvironmentFiles=%D/.env # User .env in current working directory (repo root)

[Output]
Format=disk
OutputExtension=img
ImageId=homelabian-full

[Content]
Bootable=yes  # Ensures the image is bootable
Bootloader=uki  # Uses the Unified Kernel Image

Locale=en_US.UTF-8
LocaleMessages=en_US.UTF-8
Keymap=us
Timezone=America/New_York

CleanPackageMetadata=no  # Needed to prevent removing dpkg/apt from the base image
BaseTrees=%O/homelabian-base  # Start from the homelabian-base tree rather than base debian

# Avoid loading in unnecessary kernel modules for a basic server
# KernelModules=*,-/sound/,-/drivers/media/,-/drivers/bluetooth/,-/drivers/net/wireless/,-/net/wireless/,-/net/bluetooth/,-/net/mac80211/

Packages=
    firmware-realtek        # Firmware images for proprietary ethernet/wifi cards
    firmware-iwlwifi        # Firmware images for proprietary ethernet/wifi cards
    locales
    linux-image-amd64       # Kernel image for x86-64 architecture with all modules

