
# Disable root SSH login as we have a locked down user which should add a
# layer of security. This is okay as we have a user with sudo privileges
PermitRootLogin no

# Disables password authentication for SSH, 
# requiring key-based authentication for better security.
# PasswordAuthentication no