name: mkosi build and release

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '!.github/workflows/mkosi-build.yml'

permissions:
  contents: write

jobs:
  mkosi-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1

      - name: setup-mkosi
        uses: systemd/mkosi@v26

      - name: create .env file
        run: |
          cp .env.example .env

      - name: Build image
        run: sudo mkosi -f

      - name: Calculate image size
        working-directory: build
        run: |
          FULL_RAW_SIZE=$(du -s homelabian-full*.img | cut -f1)
          FULL_READABLE_SIZE=$(du -sh homelabian-full*.img | cut -f1)

          MINI_RAW_SIZE=$(du -s homelabian-mini*.img | cut -f1)
          MINI_READABLE_SIZE=$(du -sh homelabian-mini*.img | cut -f1)

          echo "FULL_RAW_SIZE=$FULL_RAW_SIZE" | tee -a $GITHUB_ENV
          echo "FULL_READABLE_SIZE=$FULL_READABLE_SIZE" | tee -a $GITHUB_ENV
          echo "MINI_RAW_SIZE=$MINI_RAW_SIZE" | tee -a $GITHUB_ENV
          echo "MINI_READABLE_SIZE=$MINI_READABLE_SIZE" | tee -a $GITHUB_ENV

      - name: Compress images
        if: github.ref_type == 'tag'
        working-directory: build
        run: |
          FULL_FILE=$(ls homelabian-full*.img)
          MINI_FILE=$(ls homelabian-mini*.img)
          sudo chown -R $USER:$USER .
          gzip -8 "${FULL_FILE}"
          gzip -8 "${MINI_FILE}"

      - name: Release images
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          working_directory: build
          files: homelabian*.img.gz
          prerelease: true
          fail_on_unmatched_files: true
          generate_release_notes: true

      - name: Create full image size badge
        uses: schneegans/dynamic-badges-action@v1.9.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0ec3052f4bd1c320fa986de9ae312d59
          filename: img-size.json
          label: Full Image Size
          message: ${{ env.FULL_READABLE_SIZE }}
          valColorRange: ${{ env.FULL_RAW_SIZE }}
          invertColorRange: true
          maxColorRange: 4000000
          minColorRange: 0000000

      - name: Create mini image size badge
        uses: schneegans/dynamic-badges-action@v1.9.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0ec3052f4bd1c320fa986de9ae312d59
          filename: mini-size.json
          label: Mini Image Size
          message: ${{ env.MINI_READABLE_SIZE }}
          valColorRange: ${{ env.MINI_RAW_SIZE }}
          invertColorRange: true
          maxColorRange: 2000000
          minColorRange: 0000000
